#CREATING COMPANIES
Company.create(name: "VANDOR TRANS TOURS SRL", email: "office@vandortrans.ro", phone_number: "0762883716", tax_number: "49281782", city: "Gheorgheni", office_address: "Str. Kossuth Lajos nr. 91")
Company.create(name: "PANORAMA TURIST SRL", email: "panorama@gmail.com", phone_number: "0755197688", tax_number: "74112365", city: "Ditrau", office_address: "Str. Dealul frumos 73/A")
Company.create(name: "BALINT TRANS SRL", email: "balinttrans@yahoo.com", phone_number: "0723763998", tax_number: "41549877", city: "Targu Mures", office_address: "Str. Bega nr. 9")
Company.create(name: "TRANSPORT LOCAL SA", email: "office@vandortrans.ro", phone_number: "0763777716", tax_number: "87654782", city: "Targu Mures", office_address: "Str. Bega nr. 2")

#CREATING BUSES FOR THE COMPANIES
vandor = Company.find_by(name: "VANDOR TRANS TOURS SRL")
Bus.create(company_uid: vandor.company_uid, license_plate: "HR49VTT", brand: "Mercedes Integro", manufacturing_year: 2003, capacity: 73, road_tax: Date.parse("2023-12-10"), insurance: Date.parse("2023-12-22"), technical_exam: Date.parse("2023-10-10"))
Bus.create(company_uid: vandor.company_uid, license_plate: "HR22VTT", brand: "Setra S516", manufacturing_year: 2009, capacity: 57, road_tax: Date.parse("2024-04-28"), insurance: Date.parse("2024-12-02"), technical_exam: Date.parse("2024-03-03"))
Bus.create(company_uid: vandor.company_uid, license_plate: "HR56VTT", brand: "Mercedes Vario", manufacturing_year: 2019, capacity: 45, road_tax: Date.parse("2024-05-21"), insurance: Date.parse("2023-10-22"), technical_exam: Date.parse("2024-11-08"))
Bus.create(company_uid: vandor.company_uid, license_plate: "HR67VTT", brand: "Mercedes Vito", manufacturing_year: 2011, capacity: 24, road_tax: Date.parse("2024-06-29"), insurance: Date.parse("2024-01-28"), technical_exam: Date.parse("2024-06-11"))
Bus.create(company_uid: vandor.company_uid, license_plate: "HR12VTT", brand: "Otokar Sultan", manufacturing_year: 2011, capacity: 24, road_tax: Date.parse("2024-06-29"), insurance: Date.parse("2024-01-25"), technical_exam: Date.parse("2024-06-11"))
Bus.create(company_uid: vandor.company_uid, license_plate: "HR23VTT", brand: "Mercedes Sprinter", manufacturing_year: 2011, capacity: 24, road_tax: Date.parse("2024-06-11"), insurance: Date.parse("2024-06-21"), technical_exam: Date.parse("2023-10-11"))
Bus.create(company_uid: vandor.company_uid, license_plate: "HR01VTT", brand: "Mercedes Sprinter", manufacturing_year: 2020, capacity: 28, road_tax: Date.parse("2024-04-21"), insurance: Date.parse("2024-01-22"), technical_exam: Date.parse("2024-01-23"))

transloc = Company.find_by(name: "TRANSPORT LOCAL SA")
Bus.create(company_uid: transloc.company_uid, license_plate: "MS23TGM", brand: "Volvo 9700", manufacturing_year: 2010, capacity: 50, road_tax: "2024-01-15", insurance: "2024-01-25", technical_exam: "2024-01-05")
Bus.create(company_uid: transloc.company_uid, license_plate: "MS34TGM", brand: "MAN Lion's Intercity", manufacturing_year: 2012, capacity: 55, road_tax: "2024-02-15", insurance: "2024-02-25", technical_exam: "2024-02-05")
Bus.create(company_uid: transloc.company_uid, license_plate: "MS98TGM", brand: "Mercedes Integro", manufacturing_year: 2015, capacity: 60, road_tax: "2024-03-15", insurance: "2024-03-25",technical_exam: "2024-03-05")
Bus.create(company_uid: transloc.company_uid, license_plate: "MS12TGM", brand: "Mercedes Integro", manufacturing_year: 2011, capacity: 65, road_tax: "2024-04-15", insurance: "2024-04-25", technical_exam: "2024-04-05")
Bus.create(company_uid: transloc.company_uid, license_plate: "MS23MUI", brand: "Volvo B12B", manufacturing_year: 2011, capacity: 70, road_tax: "2024-05-15", insurance: "2024-05-25", technical_exam: "2024-05-05")
Bus.create(company_uid: transloc.company_uid, license_plate: "MS22UZI", brand: "Mercedes Tourismo", manufacturing_year: 2017, capacity: 75, road_tax: "2024-06-15", insurance: "2024-06-25",technical_exam: "2024-06-05")
Bus.create(company_uid: transloc.company_uid, license_plate: "MS33ALS", brand: "Neoplan Starliner", manufacturing_year: 2019, capacity: 80, road_tax: "2024-01-15", insurance: "2024-07-25",technical_exam: "2024-07-05")


#CREATING ADMINS FOR THE COMPANIES
Admin.create(company_uid: vandor.company_uid, email: "office@vandortrans.ro", firstname: "Elemér", lastname: "Kecskeméti", role: "boss", phone_number: "0728493883", address: "Com. Joseni str. Principala nr. 19", password: "aaaaaa", password_confirmation: "aaaaaa")
Admin.create(company_uid: vandor.company_uid, email: "hompoth.krisztian@gmail.com", firstname: "Krisztián", lastname: "Orsós", role: "manager", phone_number: "0761837888", address: "Com. Joseni str. Faluköze nr. 1", password: "aaaaaa", password_confirmation: "aaaaaa")
Admin.create(company_uid: vandor.company_uid, email: "csatabela@gmail.com", firstname: "Béla", lastname: "Csata", role: "driver", phone_number: "0752358475", address: "Mun. Gheorgheni str. Ghindei nr. 1", password: "aaaaaa", password_confirmation: "aaaaaa")
Admin.create(company_uid: vandor.company_uid, email: "magdi92@gmail.com", firstname: "Magdolna", lastname: "Kovács", role: "driver", phone_number: "0739489586", address: "Mun. Gheorgheni str. Stadionului nr. 4", password: "aaaaaa", password_confirmation: "aaaaaa")
Admin.create(company_uid: vandor.company_uid, email: "orsospista11@gmail.com", firstname: "István", lastname: "Orsós", role: "driver", phone_number: "0755928111", address: "Com. Ciumani str. Inczelaka nr. 1398", password: "aaaaaa", password_confirmation: "aaaaaa")
Admin.create(company_uid: vandor.company_uid, email: "ninjanarch@yahoo.com", firstname: "Iván", lastname: "Elekes", role: "driver", phone_number: "0724889734", address: "Com. Ciumani str. Principala nr. 12", password: "aaaaaa", password_confirmation: "aaaaaa")
Admin.create(company_uid: vandor.company_uid, email: "karoly_elekes@gmail.com", firstname: "Károly", lastname: "Elekes", role: "driver", phone_number: "0745399324", address: "Com. Suseni str. Kéthíd nr. 198", password: "aaaaaa", password_confirmation: "aaaaaa")

Admin.create(company_uid: transloc.company_uid, email: "office@transloctrans.ro", firstname: "Elemér", lastname: "Kecskeméti", role: "boss", phone_number: "0728493883", address: "Com. Joseni str. Principala nr. 19", password: "aaaaaa", password_confirmation: "aaaaaa")
Admin.create(company_uid: transloc.company_uid, email: "hompoth.krisztian2@gmail.com", firstname: "Krisztián", lastname: "Orsós", role: "manager", phone_number: "0761837888", address: "Com. Joseni str. Faluköze nr. 1", password: "aaaaaa", password_confirmation: "aaaaaa")
Admin.create(company_uid: transloc.company_uid, email: "csatabela2@gmail.com", firstname: "Béla", lastname: "Csata", role: "driver", phone_number: "0752358475", address: "Mun. Gheorgheni str. Ghindei nr. 1", password: "aaaaaa", password_confirmation: "aaaaaa")
Admin.create(company_uid: transloc.company_uid, email: "magdi922@gmail.com", firstname: "Magdolna", lastname: "Kovács", role: "driver", phone_number: "0739489586", address: "Mun. Gheorgheni str. Stadionului nr. 4", password: "aaaaaa", password_confirmation: "aaaaaa")
Admin.create(company_uid: transloc.company_uid, email: "orsospista112@gmail.com", firstname: "István", lastname: "Orsós", role: "driver", phone_number: "0755928111", address: "Com. Ciumani str. Inczelaka nr. 1398", password: "aaaaaa", password_confirmation: "aaaaaa")
Admin.create(company_uid: transloc.company_uid, email: "ninjanarc2h@yahoo.com", firstname: "Iván", lastname: "Elekes", role: "driver", phone_number: "0724889734", address: "Com. Ciumani str. Principala nr. 12", password: "aaaaaa", password_confirmation: "aaaaaa")
Admin.create(company_uid: transloc.company_uid, email: "2@gmail.com", firstname: "Károly", lastname: "Elekes", role: "driver", phone_number: "0745399324", address: "Com. Suseni str. Kéthíd nr. 198", password: "aaaaaa", password_confirmation: "aaaaaa")

#CREATING CITIES
ciumani = City.create(name: "Ciumani", zip_code: "537050");
joseni = City.create(name: "Joseni", zip_code: "537050");
gheorgheni = City.create(name: "Gheorgheni", zip_code: "537050");

#CREATING STATIONS
Station.create(name: "Csomafalva központ", latitude: 46.6791797, longitude: 25.515264, city: ciumani, address: "Str. Principala nr. 89")
Station.create(name: "Csomafalva szászfalu", latitude: 46.6729104, longitude: 25.4547497, city: ciumani, address: "Str. Tötés nr. 18")
Station.create(name: "Alfalu központ", latitude: 46.7002046, longitude: 25.493437, city: joseni, address: "Str. Ciumani nr. 88")
Station.create(name: "Alfalu lengyár", latitude: 46.70528, longitude: 25.5151177, city: joseni, address: "Str. Gheorgheni nr. 3")
Station.create(name: "Gyergyó állomás", latitude: 46.7164726, longitude: 25.5679183, city: gheorgheni, address: "Str. Garii nr. 16")
Station.create(name: "Gyergyó Maros hotel", latitude: 46.7209535, longitude: 25.5823401, city: gheorgheni, address: "Bul. Fratiei nr. 65")

#CREATE A ROUTE
Route.create(name: "Szászfalu-Gyergyó", company_uid: vandor.company_uid, basic_fare: 0);

route = Route.find_by(name: "Szászfalu-Gyergyó");
RouteStation.create(route: route, departure_time: Time.parse("06:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 1, fare: 0)
RouteStation.create(route: route, departure_time: Time.parse("06:05"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 2, fare: 2)
RouteStation.create(route: route, departure_time: Time.parse("06:12"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 3, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("06:18"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 4, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("06:26"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 5, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("06:30"), station: Station.find_by(name: "Gyergyó Maros hotel"), name: "Weekday", sequence: 6, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("06:34"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 7, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("06:42"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 8, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("06:50"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 9, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("06:56"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 10, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("07:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 11, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("07:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 1, fare: 0)
RouteStation.create(route: route, departure_time: Time.parse("07:05"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 2, fare: 2)
RouteStation.create(route: route, departure_time: Time.parse("07:12"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 3, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("07:18"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 4, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("07:26"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 5, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("07:30"), station: Station.find_by(name: "Gyergyó Maros hotel"), name: "Weekday", sequence: 6, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("07:34"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 7, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("07:42"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 8, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("07:50"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 9, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("07:56"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 10, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("08:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 11, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("08:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 1, fare: 0)
RouteStation.create(route: route, departure_time: Time.parse("08:05"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 2, fare: 2)
RouteStation.create(route: route, departure_time: Time.parse("08:12"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 3, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("08:18"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 4, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("08:26"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 5, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("08:30"), station: Station.find_by(name: "Gyergyó Maros hotel"), name: "Weekday", sequence: 6, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("08:34"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 7, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("08:42"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 8, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("08:50"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 9, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("08:56"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 10, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("09:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 11, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("09:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 1, fare: 0)
RouteStation.create(route: route, departure_time: Time.parse("09:05"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 2, fare: 2)
RouteStation.create(route: route, departure_time: Time.parse("09:12"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 3, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("09:18"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 4, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("09:26"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 5, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("09:30"), station: Station.find_by(name: "Gyergyó Maros hotel"), name: "Weekday", sequence: 6, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("09:34"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 7, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("09:42"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 8, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("09:50"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 9, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("09:56"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 10, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("10:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 11, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("10:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 1, fare: 0)
RouteStation.create(route: route, departure_time: Time.parse("10:05"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 2, fare: 2)
RouteStation.create(route: route, departure_time: Time.parse("10:12"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 3, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("10:18"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 4, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("10:26"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 5, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("10:30"), station: Station.find_by(name: "Gyergyó Maros hotel"), name: "Weekday", sequence: 6, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("10:34"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 7, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("10:42"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 8, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("10:50"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 9, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("10:56"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 10, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("11:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 11, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("11:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 1, fare: 0)
RouteStation.create(route: route, departure_time: Time.parse("11:05"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 2, fare: 2)
RouteStation.create(route: route, departure_time: Time.parse("11:12"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 3, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("11:18"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 4, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("11:26"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 5, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("11:30"), station: Station.find_by(name: "Gyergyó Maros hotel"), name: "Weekday", sequence: 6, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("11:34"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 7, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("11:42"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 8, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("11:50"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 9, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("11:56"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 10, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("12:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 11, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("12:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 1, fare: 0)
RouteStation.create(route: route, departure_time: Time.parse("12:05"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 2, fare: 2)
RouteStation.create(route: route, departure_time: Time.parse("12:12"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 3, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("12:18"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 4, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("12:26"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 5, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("12:30"), station: Station.find_by(name: "Gyergyó Maros hotel"), name: "Weekday", sequence: 6, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("12:34"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 7, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("12:42"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 8, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("12:50"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 9, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("12:56"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 10, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("13:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 11, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("13:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 1, fare: 0)
RouteStation.create(route: route, departure_time: Time.parse("13:05"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 2, fare: 2)
RouteStation.create(route: route, departure_time: Time.parse("13:12"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 3, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("13:18"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 4, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("13:26"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 5, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("13:30"), station: Station.find_by(name: "Gyergyó Maros hotel"), name: "Weekday", sequence: 6, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("13:34"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 7, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("13:42"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 8, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("13:50"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 9, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("13:56"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 10, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("14:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 11, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("14:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 1, fare: 0)
RouteStation.create(route: route, departure_time: Time.parse("14:05"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 2, fare: 2)
RouteStation.create(route: route, departure_time: Time.parse("14:12"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 3, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("14:18"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 4, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("14:26"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 5, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("14:30"), station: Station.find_by(name: "Gyergyó Maros hotel"), name: "Weekday", sequence: 6, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("14:34"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 7, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("14:42"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 8, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("14:50"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 9, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("14:56"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 10, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("14:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 11, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("15:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 1, fare: 0)
RouteStation.create(route: route, departure_time: Time.parse("15:05"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 2, fare: 2)
RouteStation.create(route: route, departure_time: Time.parse("15:12"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 3, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("15:18"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 4, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("15:26"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 5, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("15:30"), station: Station.find_by(name: "Gyergyó Maros hotel"), name: "Weekday", sequence: 6, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("15:34"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 7, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("15:42"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 8, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("15:50"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 9, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("15:56"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 10, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("16:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 11, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("16:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 1, fare: 0)
RouteStation.create(route: route, departure_time: Time.parse("16:05"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 2, fare: 2)
RouteStation.create(route: route, departure_time: Time.parse("16:12"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 3, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("16:18"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 4, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("16:26"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 5, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("16:30"), station: Station.find_by(name: "Gyergyó Maros hotel"), name: "Weekday", sequence: 6, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("16:34"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 7, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("16:42"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 8, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("16:50"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 9, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("16:56"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 10, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("17:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 11, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("17:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 1, fare: 0)
RouteStation.create(route: route, departure_time: Time.parse("17:05"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 2, fare: 2)
RouteStation.create(route: route, departure_time: Time.parse("17:12"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 3, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("17:18"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 4, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("17:26"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 5, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("17:30"), station: Station.find_by(name: "Gyergyó Maros hotel"), name: "Weekday", sequence: 6, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("17:34"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 7, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("17:42"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 8, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("17:50"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 9, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("17:56"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 10, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("18:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 11, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("18:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 1, fare: 0)
RouteStation.create(route: route, departure_time: Time.parse("18:05"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 2, fare: 2)
RouteStation.create(route: route, departure_time: Time.parse("18:12"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 3, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("18:18"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 4, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("18:26"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 5, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("18:30"), station: Station.find_by(name: "Gyergyó Maros hotel"), name: "Weekday", sequence: 6, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("18:34"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 7, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("18:42"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 8, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("18:50"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 9, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("18:56"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 10, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("19:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 11, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("19:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 1, fare: 0)
RouteStation.create(route: route, departure_time: Time.parse("19:05"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 2, fare: 2)
RouteStation.create(route: route, departure_time: Time.parse("19:12"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 3, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("19:18"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 4, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("19:26"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 5, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("19:30"), station: Station.find_by(name: "Gyergyó Maros hotel"), name: "Weekday", sequence: 6, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("19:34"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 7, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("19:42"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 8, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("19:50"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 9, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("19:56"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 10, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("20:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 11, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("20:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 1, fare: 0)
RouteStation.create(route: route, departure_time: Time.parse("20:05"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 2, fare: 2)
RouteStation.create(route: route, departure_time: Time.parse("20:12"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 3, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("20:18"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 4, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("20:26"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 5, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("20:30"), station: Station.find_by(name: "Gyergyó Maros hotel"), name: "Weekday", sequence: 6, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("20:34"), station: Station.find_by(name: "Gyergyó állomás"), name: "Weekday", sequence: 7, fare: 1)
RouteStation.create(route: route, departure_time: Time.parse("20:42"), station: Station.find_by(name: "Alfalu lengyár"), name: "Weekday", sequence: 8, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("20:50"), station: Station.find_by(name: "Alfalu központ"), name: "Weekday", sequence: 9, fare: 3)
RouteStation.create(route: route, departure_time: Time.parse("20:56"), station: Station.find_by(name: "Csomafalva szászfalu"), name: "Weekday", sequence: 10, fare: 4)
RouteStation.create(route: route, departure_time: Time.parse("20:00"), station: Station.find_by(name: "Csomafalva központ"), name: "Weekday", sequence: 11, fare: 4)


#CREATING TICKETS


