#CREATING COMPANIES
Company.create(name: "VANDOR TRANS TOURS SRL", email: "office@vandortrans.ro", phone_number: "0762883716", tax_number: "49281782", city: "Gheorgheni", office_address: "Str. Kossuth Lajos nr. 91")
Company.create(name: "TRANSPORT LOCAL SA", email: "office@vandortrans.ro", phone_number: "0763777716", tax_number: "87654782", city: "Targu Mures", office_address: "Str. Bega nr. 2")

#CREATING BUSES FOR THE COMPANIES
vandor = Company.find_by(name: "VANDOR TRANS TOURS SRL")
Bus.create(company_uid: vandor.company_uid, license_plate: "HR49VTT", brand: "Mercedes Integro", manufacturing_year: 2003, capacity: 73, road_tax: Date.parse("2023-12-10"), insurance: Date.parse("2023-12-22"), technical_exam: Date.parse("2023-10-10"))
Bus.create(company_uid: vandor.company_uid, license_plate: "HR22VTT", brand: "Setra S516", manufacturing_year: 2009, capacity: 57, road_tax: Date.parse("2024-04-28"), insurance: Date.parse("2024-12-02"), technical_exam: Date.parse("2024-03-03"))
Bus.create(company_uid: vandor.company_uid, license_plate: "HR56VTT", brand: "Mercedes Vario", manufacturing_year: 2019, capacity: 45, road_tax: Date.parse("2024-05-21"), insurance: Date.parse("2023-10-22"), technical_exam: Date.parse("2024-11-08"))
Bus.create(company_uid: vandor.company_uid, license_plate: "HR67VTT", brand: "Mercedes Vito", manufacturing_year: 2011, capacity: 24, road_tax: Date.parse("2024-06-29"), insurance: Date.parse("2024-01-28"), technical_exam: Date.parse("2024-06-11"))
Bus.create(company_uid: vandor.company_uid, license_plate: "HR12VTT", brand: "Otokar Sultan", manufacturing_year: 2011, capacity: 24, road_tax: Date.parse("2024-06-29"), insurance: Date.parse("2024-01-25"), technical_exam: Date.parse("2024-06-11"))
Bus.create(company_uid: vandor.company_uid, license_plate: "HR23VTT", brand: "Mercedes Sprinter", manufacturing_year: 2011, capacity: 24, road_tax: Date.parse("2024-06-11"), insurance: Date.parse("2024-06-21"), technical_exam: Date.parse("2023-10-11"))
Bus.create(company_uid: vandor.company_uid, license_plate: "HR01VTT", brand: "Mercedes Sprinter", manufacturing_year: 2020, capacity: 28, road_tax: Date.parse("2024-04-21"), insurance: Date.parse("2024-01-22"), technical_exam: Date.parse("2024-01-23"))

transloc = Company.find_by(name: "TRANSPORT LOCAL SA")
Bus.create(company_uid: transloc.company_uid, license_plate: "MS23TGM", brand: "Volvo 9700", manufacturing_year: 2010, capacity: 50, road_tax: "2024-01-15", insurance: "2024-01-25", technical_exam: "2024-01-05")
Bus.create(company_uid: transloc.company_uid, license_plate: "MS34TGM", brand: "MAN Lion's Intercity", manufacturing_year: 2012, capacity: 55, road_tax: "2024-02-15", insurance: "2024-02-25", technical_exam: "2024-02-05")
Bus.create(company_uid: transloc.company_uid, license_plate: "MS98TGM", brand: "Mercedes Integro", manufacturing_year: 2015, capacity: 60, road_tax: "2024-03-15", insurance: "2024-03-25",technical_exam: "2024-03-05")
Bus.create(company_uid: transloc.company_uid, license_plate: "MS12TGM", brand: "Mercedes Integro", manufacturing_year: 2011, capacity: 65, road_tax: "2024-04-15", insurance: "2024-04-25", technical_exam: "2024-04-05")
Bus.create(company_uid: transloc.company_uid, license_plate: "MS23MUI", brand: "Volvo B12B", manufacturing_year: 2011, capacity: 70, road_tax: "2024-05-15", insurance: "2024-05-25", technical_exam: "2024-05-05")
Bus.create(company_uid: transloc.company_uid, license_plate: "MS22UZI", brand: "Mercedes Tourismo", manufacturing_year: 2017, capacity: 75, road_tax: "2024-06-15", insurance: "2024-06-25",technical_exam: "2024-06-05")
Bus.create(company_uid: transloc.company_uid, license_plate: "MS33ALS", brand: "Neoplan Starliner", manufacturing_year: 2019, capacity: 80, road_tax: "2024-01-15", insurance: "2024-07-25",technical_exam: "2024-07-05")


#CREATING ADMINS FOR THE COMPANIES
Admin.create(company_uid: vandor.company_uid, email: "office@vandortrans.ro", firstname: "Elemér", lastname: "Kecskeméti", role: "boss", phone_number: "0728493883", address: "Com. Joseni str. Principala nr. 19", password: "aaaaaaaa", password_confirmation: "aaaaaaaa")
Admin.create(company_uid: vandor.company_uid, email: "hompoth.krisztian@gmail.com", firstname: "Krisztián", lastname: "Orsós", role: "manager", phone_number: "0761837888", address: "Com. Joseni str. Faluköze nr. 1", password: "aaaaaaaa", password_confirmation: "aaaaaaaa")
Admin.create(company_uid: vandor.company_uid, email: "csatabela@gmail.com", firstname: "Béla", lastname: "Csata", role: "driver", phone_number: "0752358475", address: "Mun. Gheorgheni str. Ghindei nr. 1", password: "aaaaaaaa", password_confirmation: "aaaaaaaa")
Admin.create(company_uid: vandor.company_uid, email: "magdi92@gmail.com", firstname: "Magdolna", lastname: "Kovács", role: "driver", phone_number: "0739489586", address: "Mun. Gheorgheni str. Stadionului nr. 4", password: "aaaaaaaa", password_confirmation: "aaaaaaaa")
Admin.create(company_uid: vandor.company_uid, email: "orsospista11@gmail.com", firstname: "István", lastname: "Orsós", role: "driver", phone_number: "0755928111", address: "Com. Ciumani str. Inczelaka nr. 1398", password: "aaaaaaaa", password_confirmation: "aaaaaaaa")
Admin.create(company_uid: vandor.company_uid, email: "ninjanarch@yahoo.com", firstname: "Iván", lastname: "Elekes", role: "driver", phone_number: "0724889734", address: "Com. Ciumani str. Principala nr. 12", password: "aaaaaaaa", password_confirmation: "aaaaaaaa")
Admin.create(company_uid: vandor.company_uid, email: "karoly_elekes@gmail.com", firstname: "Károly", lastname: "Elekes", role: "driver", phone_number: "0745399324", address: "Com. Suseni str. Kéthíd nr. 198", password: "aaaaaaaa", password_confirmation: "aaaaaaaa")

Admin.create(company_uid: transloc.company_uid, email: "office@transloctrans.ro", firstname: "Elemér", lastname: "Kecskeméti", role: "boss", phone_number: "0728493883", address: "Com. Joseni str. Principala nr. 19", password: "aaaaaa", password_confirmation: "aaaaaa")
Admin.create(company_uid: transloc.company_uid, email: "hompoth.krisztian2@gmail.com", firstname: "Krisztián", lastname: "Orsós", role: "manager", phone_number: "0761837888", address: "Com. Joseni str. Faluköze nr. 1", password: "aaaaaa", password_confirmation: "aaaaaa")
Admin.create(company_uid: transloc.company_uid, email: "csatabela2@gmail.com", firstname: "Béla", lastname: "Csata", role: "driver", phone_number: "0752358475", address: "Mun. Gheorgheni str. Ghindei nr. 1", password: "aaaaaa", password_confirmation: "aaaaaa")
Admin.create(company_uid: transloc.company_uid, email: "magdi922@gmail.com", firstname: "Magdolna", lastname: "Kovács", role: "driver", phone_number: "0739489586", address: "Mun. Gheorgheni str. Stadionului nr. 4", password: "aaaaaa", password_confirmation: "aaaaaa")
Admin.create(company_uid: transloc.company_uid, email: "orsospista112@gmail.com", firstname: "István", lastname: "Orsós", role: "driver", phone_number: "0755928111", address: "Com. Ciumani str. Inczelaka nr. 1398", password: "aaaaaa", password_confirmation: "aaaaaa")
Admin.create(company_uid: transloc.company_uid, email: "ninjanarc2h@yahoo.com", firstname: "Iván", lastname: "Elekes", role: "driver", phone_number: "0724889734", address: "Com. Ciumani str. Principala nr. 12", password: "aaaaaa", password_confirmation: "aaaaaa")
Admin.create(company_uid: transloc.company_uid, email: "2@gmail.com", firstname: "Károly", lastname: "Elekes", role: "driver", phone_number: "0745399324", address: "Com. Suseni str. Kéthíd nr. 198", password: "aaaaaa", password_confirmation: "aaaaaa")

#CREATING CITIES
ciumani = City.create(name: "Ciumani", zip_code: "537050")
joseni = City.create(name: "Joseni", zip_code: "537150")
gheorgheni = City.create(name: "Gheorgheni", zip_code: "117050")
tgm = City.create(name: "Targu mures", zip_code: "129138")
praid = City.create(name: "Praid", zip_code: "382983")

#CREATING STATIONS
Station.create(name: "Csomafalva Központ", latitude: 46.6791586975964, longitude: 25.51624828632996, city: ciumani, address: "Str. Principala nr. 89")
Station.create(name: "Csomafalva Szászfalu", latitude: 46.67291081146523, longitude: 25.49966790502754, city: ciumani, address: "Str. Töltés nr. 18")
Station.create(name: "Alfalu Központ", latitude: 46.701383449930674, longitude: 25.504336705477453, city: joseni, address: "Str. Ciumani nr. 88")
Station.create(name: "Alfalu Lengyár", latitude: 46.7061202738582, longitude: 25.527403454222306, city: joseni, address: "Str. Gheorgheni nr. 3")
Station.create(name: "Gyergyó Állomás", latitude: 46.719521757528696, longitude: 25.5740503955354, city: gheorgheni, address: "Str. Garii nr. 16")
Station.create(name: "Gyergyó Maros hotel", latitude: 46.722678965669736, longitude: 25.59475044928773, city: gheorgheni, address: "Bul. Fratiei nr. 65")
Station.create(name: "Gyergyó Központ", latitude: 46.720802603020786, longitude: 25.599988435400288, city: gheorgheni, address: "Pta. Libertatii nr. 26")

Station.create(name: "Sapientia", latitude: 46.52339, longitude: 24.59883, city: tgm, address: "Str. Calea Sighisoarei nr. 2")
Station.create(name: "Dedeman", latitude: 46.52678, longitude: 24.59941, city: tgm, address: "Bul. 1 Decembrie nr. 189")
Station.create(name: "Regele Ferdinand", latitude: 46.53422, longitude: 24.59133, city: tgm, address: "Str. Livezeni nr. 32")
Station.create(name: "Piata Diamant 1", latitude: 46.53736, longitude: 24.59033, city: tgm, address: "Str. Cutezantei nr. 12")
Station.create(name: "Infratirii", latitude: 46.53851, longitude: 24.58423, city: tgm, address: "Str. infratirii nr. 78")
Station.create(name: "Fortuna", latitude: 46.53560, longitude: 24.58276, city: tgm, address: "Bul. 1 Decembrie nr. 117")
Station.create(name: "Lalelelor", latitude: 46.53908, longitude: 24.57623, city: tgm, address: "Bul. 1 Decembrie nr. 93")
Station.create(name: "Izvor", latitude: 46.53967, longitude: 24.56045, city: tgm, address: "Bul. 1 Decembrie nr. 59")
Station.create(name: "Grand", latitude: 46.54195, longitude: 24.55786, city: tgm, address: "Piata Vitoriei nr. 4")
Station.create(name: "Piata Trandafirilor", latitude: 46.54377, longitude: 24.56029, city: tgm, address: "Piata Trandafirilor nr. 10")
Station.create(name: "Evidenta Populatiei", latitude: 46.54757, longitude: 24.56036, city: tgm, address: "Str. Calarasilor nr. 48")
Station.create(name: "Cocosul de Aur", latitude: 46.55060, longitude: 24.55606, city: tgm, address: "Str. Calarasilor nr. 81")
Station.create(name: "Aleea Carpati 2", latitude: 46.55300, longitude: 24.55728, city: tgm, address: "Str. Aleea Carpati nr. 17")
Station.create(name: "Strandul 1 Mai", latitude: 46.55674, longitude: 24.56346, city: tgm, address: "Str. Aleea Carpati nr. 93")
Station.create(name: "Aleea Carpati 1", latitude: 46.55456, longitude: 24.55977, city: tgm, address: "Str. Aleea Carpati nr. 32")
Station.create(name: "Darina", latitude: 46.55363, longitude: 24.55819, city: tgm, address: "")
Station.create(name: "Piata de Vechituri", latitude: 46.55313, longitude: 24.55179, city: tgm, address: "Str. Insulei nr. 3")
Station.create(name: "Electrica", latitude: 46.55041, longitude: 24.55600, city: tgm, address: "Str Calarasilor nr. 11")
Station.create(name: "Evreilor Martiri", latitude: 46.54814, longitude: 24.55849, city: tgm, address: "Str. Calarasilor nr. 23")
Station.create(name: "Piata Teatrului", latitude: 46.54563, longitude: 24.56196, city: tgm, address: "Piata Trandafirilor nr. 11")
Station.create(name: "Poli 2", latitude: 46.53940, longitude: 24.56104, city: tgm, address: "Bul. 1 Decembrie nr. 26")
Station.create(name: "Europa", latitude: 46.53886, longitude: 24.57537, city: tgm, address: "Bul. 1 Decembrie nr. 48")
Station.create(name: "Poklos", latitude: 46.53768, longitude: 24.58447, city: tgm, address: "Str. Infratirii nr. 82")
Station.create(name: "Tudor Vladimirescu", latitude: 46.53892, longitude: 24.58686, city: tgm, address: "Str. Cutezanzei nr. 183")
Station.create(name: "Piata Diamant 2", latitude: 46.53674, longitude: 46.53674, city: tgm, address: "Str. Cutezantei nr. 83")
Station.create(name: "Liceul Electromures", latitude: 46.53404, longitude: 24.59039, city: tgm, address: "Str. Livezeni nr. 8")
Station.create(name: "Corina 2", latitude: 46.53256, longitude: 24.58980, city: tgm, address: "Bul. 1 Decembrie nr. 173")
Station.create(name: "Shopping City", latitude: 46.52830, longitude: 24.59659, city: tgm, address: "Bul. 1 Decembrie fara numar")
Station.create(name: "Hotel Business", latitude: 46.52687, longitude: 24.59910, city: tgm, address: "")


#CREATE A ROUTE
Route.create(name: "Szászfalu-Gyergyó", company_uid: vandor.company_uid, nr_of_stations: 10, basic_fare: 0);
Route.create(name: "Gyergyó-Marosvásárhely", company_uid: vandor.company_uid, nr_of_stations: , basic_fare: 0);
Route.create(name: "26", company_uid: transloc.company_uid, nr_of_stations: 27, basic_fare: 2);

route = Route.find_by(name: "Szászfalu-Gyergyó");
rs1 = RouteStation.create(route: route, station: Station.find_by(company: vandor, name: "Csomafalva szászfalu"), sequence: 1)
rs2 = RouteStation.create(route: route, station: Station.find_by(company: vandor, name: "Csomafalva központ"), sequence: 2)
rs3 = RouteStation.create(route: route, station: Station.find_by(company: vandor, name: "Alfalu központ"), sequence: 3)
rs4 = RouteStation.create(route: route, station: Station.find_by(company: vandor, name: "Alfalu lengyár"), sequence: 4)
rs5 = RouteStation.create(route: route, station: Station.find_by(company: vandor, name: "Gyergyó állomás"), sequence: 5)
rs6 = RouteStation.create(route: route, station: Station.find_by(company: vandor, name: "Gyergyó Maros hotel"), sequence: 6)
rs7 = RouteStation.create(route: route, station: Station.find_by(company: vandor, name: "Gyergyó állomás"), sequence: 7)
rs8 = RouteStation.create(route: route, station: Station.find_by(company: vandor, name: "Alfalu lengyár"), sequence: 8)
rs9 = RouteStation.create(route: route, station: Station.find_by(company: vandor, name: "Alfalu központ"), sequence: 9)
rs10 = RouteStation.create(route: route,station: Station.find_by(company: vandor, name: "Csomafalva központ"), sequence: 10)

weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
weekends = ["Saturday", "Sunday"]


weekdays.each do |name|
    Timetable.create(route_station: rs1, departure_time: Time.parse("06:00"), fare: 0, name: name )
    Timetable.create(route_station: rs1, departure_time: Time.parse("07:00"), fare: 0, name: name )
    Timetable.create(route_station: rs1, departure_time: Time.parse("08:00"), fare: 0, name: name )
    Timetable.create(route_station: rs1, departure_time: Time.parse("09:00"), fare: 0, name: name )
    Timetable.create(route_station: rs1, departure_time: Time.parse("10:00"), fare: 0, name: name )
    Timetable.create(route_station: rs1, departure_time: Time.parse("11:00"), fare: 0, name: name )
    Timetable.create(route_station: rs1, departure_time: Time.parse("12:00"), fare: 0, name: name )
    Timetable.create(route_station: rs1, departure_time: Time.parse("13:00"), fare: 0, name: name )
    Timetable.create(route_station: rs1, departure_time: Time.parse("14:00"), fare: 0, name: name )
    Timetable.create(route_station: rs1, departure_time: Time.parse("15:00"), fare: 0, name: name )
    Timetable.create(route_station: rs1, departure_time: Time.parse("16:00"), fare: 0, name: name )
    Timetable.create(route_station: rs1, departure_time: Time.parse("17:00"), fare: 0, name: name )
    Timetable.create(route_station: rs1, departure_time: Time.parse("18:00"), fare: 0, name: name )
    Timetable.create(route_station: rs1, departure_time: Time.parse("19:00"), fare: 0, name: name )
    Timetable.create(route_station: rs1, departure_time: Time.parse("20:00"), fare: 0, name: name )
    Timetable.create(route_station: rs2, departure_time: Time.parse("06:05"), fare: 2, name: name )
    Timetable.create(route_station: rs2, departure_time: Time.parse("07:05"), fare: 2, name: name )
    Timetable.create(route_station: rs2, departure_time: Time.parse("08:05"), fare: 2, name: name )
    Timetable.create(route_station: rs2, departure_time: Time.parse("09:05"), fare: 2, name: name )
    Timetable.create(route_station: rs2, departure_time: Time.parse("10:05"), fare: 2, name: name )
    Timetable.create(route_station: rs2, departure_time: Time.parse("11:05"), fare: 2, name: name )
    Timetable.create(route_station: rs2, departure_time: Time.parse("12:05"), fare: 2, name: name )
    Timetable.create(route_station: rs2, departure_time: Time.parse("13:05"), fare: 2, name: name )
    Timetable.create(route_station: rs2, departure_time: Time.parse("14:05"), fare: 2, name: name )
    Timetable.create(route_station: rs2, departure_time: Time.parse("15:05"), fare: 2, name: name )
    Timetable.create(route_station: rs2, departure_time: Time.parse("16:05"), fare: 2, name: name )
    Timetable.create(route_station: rs2, departure_time: Time.parse("17:05"), fare: 2, name: name )
    Timetable.create(route_station: rs2, departure_time: Time.parse("18:05"), fare: 2, name: name )
    Timetable.create(route_station: rs2, departure_time: Time.parse("19:05"), fare: 2, name: name )
    Timetable.create(route_station: rs2, departure_time: Time.parse("20:05"), fare: 2, name: name )
    Timetable.create(route_station: rs3, departure_time: Time.parse("06:12"), fare: 4, name: name )
    Timetable.create(route_station: rs3, departure_time: Time.parse("07:12"), fare: 4, name: name )
    Timetable.create(route_station: rs3, departure_time: Time.parse("08:12"), fare: 4, name: name )
    Timetable.create(route_station: rs3, departure_time: Time.parse("09:12"), fare: 4, name: name )
    Timetable.create(route_station: rs3, departure_time: Time.parse("10:12"), fare: 4, name: name )
    Timetable.create(route_station: rs3, departure_time: Time.parse("11:12"), fare: 4, name: name )
    Timetable.create(route_station: rs3, departure_time: Time.parse("12:12"), fare: 4, name: name )
    Timetable.create(route_station: rs3, departure_time: Time.parse("13:12"), fare: 4, name: name )
    Timetable.create(route_station: rs3, departure_time: Time.parse("14:12"), fare: 4, name: name )
    Timetable.create(route_station: rs3, departure_time: Time.parse("15:12"), fare: 4, name: name )
    Timetable.create(route_station: rs3, departure_time: Time.parse("16:12"), fare: 4, name: name )
    Timetable.create(route_station: rs3, departure_time: Time.parse("17:12"), fare: 4, name: name )
    Timetable.create(route_station: rs3, departure_time: Time.parse("18:12"), fare: 4, name: name )
    Timetable.create(route_station: rs3, departure_time: Time.parse("19:12"), fare: 4, name: name )
    Timetable.create(route_station: rs3, departure_time: Time.parse("20:12"), fare: 4, name: name )
    Timetable.create(route_station: rs4, departure_time: Time.parse("07:18"), fare: 3, name: name )
    Timetable.create(route_station: rs4, departure_time: Time.parse("08:18"), fare: 3, name: name )
    Timetable.create(route_station: rs4, departure_time: Time.parse("09:18"), fare: 3, name: name )
    Timetable.create(route_station: rs4, departure_time: Time.parse("10:18"), fare: 3, name: name )
    Timetable.create(route_station: rs4, departure_time: Time.parse("11:18"), fare: 3, name: name )
    Timetable.create(route_station: rs4, departure_time: Time.parse("12:18"), fare: 3, name: name )
    Timetable.create(route_station: rs4, departure_time: Time.parse("13:18"), fare: 3, name: name )
    Timetable.create(route_station: rs4, departure_time: Time.parse("14:18"), fare: 3, name: name )
    Timetable.create(route_station: rs4, departure_time: Time.parse("15:18"), fare: 3, name: name )
    Timetable.create(route_station: rs4, departure_time: Time.parse("16:18"), fare: 3, name: name )
    Timetable.create(route_station: rs4, departure_time: Time.parse("17:18"), fare: 3, name: name )
    Timetable.create(route_station: rs4, departure_time: Time.parse("18:18"), fare: 3, name: name )
    Timetable.create(route_station: rs4, departure_time: Time.parse("19:18"), fare: 3, name: name )
    Timetable.create(route_station: rs4, departure_time: Time.parse("20:18"), fare: 3, name: name )
    Timetable.create(route_station: rs5, departure_time: Time.parse("06:26"), fare: 3, name: name )
    Timetable.create(route_station: rs5, departure_time: Time.parse("07:26"), fare: 3, name: name )
    Timetable.create(route_station: rs5, departure_time: Time.parse("08:26"), fare: 3, name: name )
    Timetable.create(route_station: rs5, departure_time: Time.parse("09:26"), fare: 3, name: name )
    Timetable.create(route_station: rs5, departure_time: Time.parse("10:26"), fare: 3, name: name )
    Timetable.create(route_station: rs5, departure_time: Time.parse("11:26"), fare: 3, name: name )
    Timetable.create(route_station: rs5, departure_time: Time.parse("12:26"), fare: 3, name: name )
    Timetable.create(route_station: rs5, departure_time: Time.parse("13:26"), fare: 3, name: name )
    Timetable.create(route_station: rs5, departure_time: Time.parse("14:26"), fare: 3, name: name )
    Timetable.create(route_station: rs5, departure_time: Time.parse("15:26"), fare: 3, name: name )
    Timetable.create(route_station: rs5, departure_time: Time.parse("16:26"), fare: 3, name: name )
    Timetable.create(route_station: rs5, departure_time: Time.parse("17:26"), fare: 3, name: name )
    Timetable.create(route_station: rs5, departure_time: Time.parse("18:26"), fare: 3, name: name )
    Timetable.create(route_station: rs5, departure_time: Time.parse("19:26"), fare: 3, name: name )
    Timetable.create(route_station: rs5, departure_time: Time.parse("20:26"), fare: 3, name: name )
    Timetable.create(route_station: rs6, departure_time: Time.parse("06:30"), fare: 1, name: name )
    Timetable.create(route_station: rs6, departure_time: Time.parse("07:30"), fare: 1, name: name )
    Timetable.create(route_station: rs6, departure_time: Time.parse("08:30"), fare: 1, name: name )
    Timetable.create(route_station: rs6, departure_time: Time.parse("09:30"), fare: 1, name: name )
    Timetable.create(route_station: rs6, departure_time: Time.parse("10:30"), fare: 1, name: name )
    Timetable.create(route_station: rs6, departure_time: Time.parse("11:30"), fare: 1, name: name )
    Timetable.create(route_station: rs6, departure_time: Time.parse("12:30"), fare: 1, name: name )
    Timetable.create(route_station: rs6, departure_time: Time.parse("13:30"), fare: 1, name: name )
    Timetable.create(route_station: rs6, departure_time: Time.parse("14:30"), fare: 1, name: name )
    Timetable.create(route_station: rs6, departure_time: Time.parse("15:30"), fare: 1, name: name )
    Timetable.create(route_station: rs6, departure_time: Time.parse("16:30"), fare: 1, name: name )
    Timetable.create(route_station: rs6, departure_time: Time.parse("17:30"), fare: 1, name: name )
    Timetable.create(route_station: rs6, departure_time: Time.parse("18:30"), fare: 1, name: name )
    Timetable.create(route_station: rs6, departure_time: Time.parse("19:30"), fare: 1, name: name )
    Timetable.create(route_station: rs6, departure_time: Time.parse("20:30"), fare: 1, name: name )
    Timetable.create(route_station: rs7, departure_time: Time.parse("06:34"), fare: 1, name: name )
    Timetable.create(route_station: rs7, departure_time: Time.parse("07:34"), fare: 1, name: name )
    Timetable.create(route_station: rs7, departure_time: Time.parse("08:34"), fare: 1, name: name )
    Timetable.create(route_station: rs7, departure_time: Time.parse("09:34"), fare: 1, name: name )
    Timetable.create(route_station: rs7, departure_time: Time.parse("10:34"), fare: 1, name: name )
    Timetable.create(route_station: rs7, departure_time: Time.parse("11:34"), fare: 1, name: name )
    Timetable.create(route_station: rs7, departure_time: Time.parse("12:34"), fare: 1, name: name )
    Timetable.create(route_station: rs7, departure_time: Time.parse("13:34"), fare: 1, name: name )
    Timetable.create(route_station: rs7, departure_time: Time.parse("14:34"), fare: 1, name: name )
    Timetable.create(route_station: rs7, departure_time: Time.parse("15:34"), fare: 1, name: name )
    Timetable.create(route_station: rs7, departure_time: Time.parse("16:34"), fare: 1, name: name )
    Timetable.create(route_station: rs7, departure_time: Time.parse("17:34"), fare: 1, name: name )
    Timetable.create(route_station: rs7, departure_time: Time.parse("18:34"), fare: 1, name: name )
    Timetable.create(route_station: rs7, departure_time: Time.parse("19:34"), fare: 1, name: name )
    Timetable.create(route_station: rs7, departure_time: Time.parse("20:34"), fare: 1, name: name )
    Timetable.create(route_station: rs8, departure_time: Time.parse("06:42"), fare: 3, name: name )
    Timetable.create(route_station: rs8, departure_time: Time.parse("07:42"), fare: 3, name: name )
    Timetable.create(route_station: rs8, departure_time: Time.parse("08:42"), fare: 3, name: name )
    Timetable.create(route_station: rs8, departure_time: Time.parse("09:42"), fare: 3, name: name )
    Timetable.create(route_station: rs8, departure_time: Time.parse("10:42"), fare: 3, name: name )
    Timetable.create(route_station: rs8, departure_time: Time.parse("11:42"), fare: 3, name: name )
    Timetable.create(route_station: rs8, departure_time: Time.parse("12:42"), fare: 3, name: name )
    Timetable.create(route_station: rs8, departure_time: Time.parse("13:42"), fare: 3, name: name )
    Timetable.create(route_station: rs8, departure_time: Time.parse("14:42"), fare: 3, name: name )
    Timetable.create(route_station: rs8, departure_time: Time.parse("15:42"), fare: 3, name: name )
    Timetable.create(route_station: rs8, departure_time: Time.parse("16:42"), fare: 3, name: name )
    Timetable.create(route_station: rs8, departure_time: Time.parse("17:42"), fare: 3, name: name )
    Timetable.create(route_station: rs8, departure_time: Time.parse("18:42"), fare: 3, name: name )
    Timetable.create(route_station: rs8, departure_time: Time.parse("19:42"), fare: 3, name: name )
    Timetable.create(route_station: rs8, departure_time: Time.parse("20:42"), fare: 3, name: name )
    Timetable.create(route_station: rs9, departure_time: Time.parse("06:50"), fare: 3, name: name )
    Timetable.create(route_station: rs9, departure_time: Time.parse("07:50"), fare: 3, name: name )
    Timetable.create(route_station: rs9, departure_time: Time.parse("08:50"), fare: 3, name: name )
    Timetable.create(route_station: rs9, departure_time: Time.parse("09:50"), fare: 3, name: name )
    Timetable.create(route_station: rs9, departure_time: Time.parse("10:50"), fare: 3, name: name )
    Timetable.create(route_station: rs9, departure_time: Time.parse("11:50"), fare: 3, name: name )
    Timetable.create(route_station: rs9, departure_time: Time.parse("12:50"), fare: 3, name: name )
    Timetable.create(route_station: rs9, departure_time: Time.parse("13:50"), fare: 3, name: name )
    Timetable.create(route_station: rs9, departure_time: Time.parse("14:50"), fare: 3, name: name )
    Timetable.create(route_station: rs9, departure_time: Time.parse("15:50"), fare: 3, name: name )
    Timetable.create(route_station: rs9, departure_time: Time.parse("16:50"), fare: 3, name: name )
    Timetable.create(route_station: rs9, departure_time: Time.parse("17:50"), fare: 3, name: name )
    Timetable.create(route_station: rs9, departure_time: Time.parse("18:50"), fare: 3, name: name )
    Timetable.create(route_station: rs9, departure_time: Time.parse("19:50"), fare: 3, name: name )
    Timetable.create(route_station: rs9, departure_time: Time.parse("20:50"), fare: 3, name: name )
    Timetable.create(route_station: rs10, departure_time: Time.parse("06:56"), fare: 4, name: name )
    Timetable.create(route_station: rs10, departure_time: Time.parse("07:56"), fare: 4, name: name )
    Timetable.create(route_station: rs10, departure_time: Time.parse("08:56"), fare: 4, name: name )
    Timetable.create(route_station: rs10, departure_time: Time.parse("09:56"), fare: 4, name: name )
    Timetable.create(route_station: rs10, departure_time: Time.parse("10:56"), fare: 4, name: name )
    Timetable.create(route_station: rs10, departure_time: Time.parse("11:56"), fare: 4, name: name )
    Timetable.create(route_station: rs10, departure_time: Time.parse("12:56"), fare: 4, name: name )
    Timetable.create(route_station: rs10, departure_time: Time.parse("13:56"), fare: 4, name: name )
    Timetable.create(route_station: rs10, departure_time: Time.parse("14:56"), fare: 4, name: name )
    Timetable.create(route_station: rs10, departure_time: Time.parse("15:56"), fare: 4, name: name )
    Timetable.create(route_station: rs10, departure_time: Time.parse("16:56"), fare: 4, name: name )
    Timetable.create(route_station: rs10, departure_time: Time.parse("17:56"), fare: 4, name: name )
    Timetable.create(route_station: rs10, departure_time: Time.parse("18:56"), fare: 4, name: name )
    Timetable.create(route_station: rs10, departure_time: Time.parse("19:56"), fare: 4, name: name )
    Timetable.create(route_station: rs10, departure_time: Time.parse("20:56"), fare: 4, name: name )
end


weekends.each do |name|
    Timetable.create(route_station: rs1, departure_time: Time.parse("07:00"), fare: 0, name: name)
    Timetable.create(route_station: rs1, departure_time: Time.parse("18:00"), fare: 0, name: name)
    Timetable.create(route_station: rs2, departure_time: Time.parse("07:05"), fare: 2, name: name )
    Timetable.create(route_station: rs2, departure_time: Time.parse("18:05"), fare: 2, name: name )
    Timetable.create(route_station: rs3, departure_time: Time.parse("07:12"), fare: 4, name: name )
    Timetable.create(route_station: rs3, departure_time: Time.parse("18:12"), fare: 4, name: name )
    Timetable.create(route_station: rs4, departure_time: Time.parse("07:18"), fare: 3, name: name )
    Timetable.create(route_station: rs4, departure_time: Time.parse("18:18"), fare: 3, name: name )
    Timetable.create(route_station: rs5, departure_time: Time.parse("07:26"), fare: 3, name: name )
    Timetable.create(route_station: rs5, departure_time: Time.parse("18:26"), fare: 3, name: name )
    Timetable.create(route_station: rs6, departure_time: Time.parse("07:30"), fare: 1, name: name )
    Timetable.create(route_station: rs6, departure_time: Time.parse("18:30"), fare: 1, name: name )
    Timetable.create(route_station: rs7, departure_time: Time.parse("07:34"), fare: 1, name: name )
    Timetable.create(route_station: rs7, departure_time: Time.parse("18:34"), fare: 1, name: name )
    Timetable.create(route_station: rs8, departure_time: Time.parse("07:42"), fare: 3, name: name )
    Timetable.create(route_station: rs8, departure_time: Time.parse("18:42"), fare: 3, name: name )
    Timetable.create(route_station: rs9, departure_time: Time.parse("07:50"), fare: 3, name: name )
    Timetable.create(route_station: rs9, departure_time: Time.parse("18:50"), fare: 3, name: name )
    Timetable.create(route_station: rs10, departure_time: Time.parse("07:56"), fare: 4, name: name )
    Timetable.create(route_station: rs10, departure_time: Time.parse("18:56"), fare: 4, name: name )
end

route = Route.find_by(name: "Gyergyó-Marosvásárhely");
rs1 = RouteStation.create(route: route, station: Station.find_by(company: vandor, name: "Gyergyó központ"), sequence: 1)
rs2 = RouteStation.create(route: route, station: Station.find_by(company: vandor, name: "Gyegyó állomás"), sequence: 2)
rs3 = RouteStation.create(route: route, station: Station.find_by(company: vandor, name: "Parajd központ"), sequence: 3)
rs4 = RouteStation.create(route: route, station: Station.find_by(company: vandor, name: "Dedeman"), sequence: 4)
rs5 = RouteStation.create(route: route, station: Station.find_by(company: vandor, name: "Piata Trandafirilor"), sequence: 5)
rs6 = RouteStation.create(route: route, station: Station.find_by(company: vandor, name: "Dedeman"), sequence: 6)
rs7 = RouteStation.create(route: route, station: Station.find_by(company: vandor, name: "Parajd központ"), sequence: 7)
rs8 = RouteStation.create(route: route, station: Station.find_by(company: vandor, name: "Gyergyó állomás"), sequence: 8)

weekdays.each do |name|
    Timetable.create(route_station: rs1, departure_time: Time.parse("06:00"), fare: 0, name: name )
    Timetable.create(route_station: rs1, departure_time: Time.parse("18:00"), fare: 0, name: name )
    Timetable.create(route_station: rs2, departure_time: Time.parse("06:05"), fare: 2, name: name )
    Timetable.create(route_station: rs2, departure_time: Time.parse("18:05"), fare: 2, name: name )
    Timetable.create(route_station: rs3, departure_time: Time.parse("07:00"), fare: 18, name: name )
    Timetable.create(route_station: rs3, departure_time: Time.parse("19:00"), fare: 18, name: name )
    Timetable.create(route_station: rs4, departure_time: Time.parse("07:45"), fare: 20, name: name )
    Timetable.create(route_station: rs4, departure_time: Time.parse("19:45"), fare: 20, name: name )
    Timetable.create(route_station: rs5, departure_time: Time.parse("08:00"), fare: 1, name: name )
    Timetable.create(route_station: rs5, departure_time: Time.parse("20:00"), fare: 1, name: name )
    Timetable.create(route_station: rs6, departure_time: Time.parse("08:15"), fare: 1, name: name )
    Timetable.create(route_station: rs6, departure_time: Time.parse("20:15"), fare: 1, name: name )
    Timetable.create(route_station: rs7, departure_time: Time.parse("9:00"), fare: 20, name: name )
    Timetable.create(route_station: rs7, departure_time: Time.parse("21:00"), fare: 20, name: name )
    Timetable.create(route_station: rs8, departure_time: Time.parse("10:00"), fare: 18, name: name )
    Timetable.create(route_station: rs8, departure_time: Time.parse("22:00"), fare: 18, name: name )
end

route = Route.find_by(name: "26")

rs1 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Sapientia"), sequence: )
rs2 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Dedeman"), sequence: )
rs3 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Regele Ferdinand"), sequence: )
rs4 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Piata Diamant 1"), sequence: )
rs5 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Infratirii"), sequence: )
rs6 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Fortuna"), sequence: )
rs7 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Lalelelor"), sequence: )
rs8 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Izvor"), sequence: )
rs9 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Grand"), sequence: )
rs10 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Piata Trandafirilor"), sequence: )
rs11 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Evidenta Populatiei"), sequence: )
rs12 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Cocosul de Aur"), sequence: )
rs13 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Aleea Carpati 2"), sequence: )
rs14 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Strandul 1 Mai"), sequence: )
rs15 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Aleea Carpati "), sequence: )
rs16 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Darina"), sequence: )
rs17 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Piata de Vechituri"), sequence: )
rs18 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Electrica"), sequence: )
rs19 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Evreilor Martiri"), sequence: )
rs20 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Piata Teatrului"), sequence: )
rs21 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Poli 2"), sequence: )
rs22 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Europa"), sequence: )
rs23 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Poklos"), sequence: )
rs24 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Tudor Vladimirescu"), sequence: )
rs25 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Piata Diamant 2"), sequence: )
rs26 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Liceul Electromures"), sequence: )
rs27 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Corina 2"), sequence: )
rs28 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Shopping City"), sequence: )
rs29 = RouteStation.create(route: route, station: Station.find_by(company: transloc, name: "Hotel Business"), sequence: )

#CREATING TICKETS

