default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  <<: *default
  host: localhost
  database: bus4u_test
  username: bus4u
  password: thesisdb123.

development:
  <<: *default
  host: <%= Rails.application.credentials.dig(:db_host) %>
  database: <%= Rails.application.credentials.dig(:db_database) %>
  username: <%= Rails.application.credentials.dig(:db_username) %>
  password: <%= Rails.application.credentials.dig(:db_password) %>

production:
  <<: *default
  host: <%= Rails.application.credentials.dig(:db_host) %>
  database: <%= Rails.application.credentials.dig(:db_database) %>
  username: <%= Rails.application.credentials.dig(:db_username) %>
  password: <%= Rails.application.credentials.dig(:db_password) %>