name: Cypress tests
on: push
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress test USER
        uses: cypress-io/github-action@v6
        env:
          VITE_MAPBOX_TOKEN: ${{ secrets.VITE_MAPBOX_TOKEN }}
        with:
          start: npm run dev
          working-directory: USER_WEB
      - name: Cypress test ADMIN
        uses: cypress-io/github-action@v6
        if: success() || failure()
        env:
          VITE_MAPBOX_TOKEN: ${{ secrets.VITE_MAPBOX_TOKEN }}
        with:
          start: npm run dev
          working-directory: ADMIN_WEB
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: |
            USER_WEB/cypress/screenshots
            ADMIN_WEB/cypress/screenshots
          overwrite: true
